# Generated by Django 3.0 on 2020-10-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackboards', '0002_auto_20201021_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='listtableitem',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
