# Generated by Django 3.0 on 2020-10-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blackboards', '0003_listtableitem_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listtable',
            name='table_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
