# Generated by Django 3.0 on 2022-12-24 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blackboards', '0006_board_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='board_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
